using UnityEngine;
using System.Collections.Generic;

namespace BloodRing.Art
{
    /// <summary>
    /// Central runtime access point for all hand-generated Blood Ring art that
    /// lives under Assets/Resources/Art. Every sprite/texture returned here is a
    /// real, pre-authored PNG shipped with the project - nothing is generated by
    /// code at runtime. Game systems query art by logical key and category so the
    /// underlying file layout can change without touching gameplay code.
    /// </summary>
    public static class BloodRingArtLibrary
    {
        public const string Root = "Art";

        private static readonly Dictionary<string, Texture2D> _texCache = new Dictionary<string, Texture2D>();
        private static readonly Dictionary<string, Sprite> _spriteCache = new Dictionary<string, Sprite>();

        /// <summary>Load a raw texture by its path relative to Resources/Art (no extension).</summary>
        public static Texture2D LoadTexture(string relativePath)
        {
            if (string.IsNullOrEmpty(relativePath)) return null;
            if (_texCache.TryGetValue(relativePath, out var cached) && cached != null) return cached;
            Texture2D tex = Resources.Load<Texture2D>(Root + "/" + relativePath);
            if (tex != null) _texCache[relativePath] = tex;
            return tex;
        }

        /// <summary>Load (and cache) a sprite built from an Art texture.</summary>
        public static Sprite LoadSprite(string relativePath)
        {
            if (string.IsNullOrEmpty(relativePath)) return null;
            if (_spriteCache.TryGetValue(relativePath, out var cached) && cached != null) return cached;

            // Prefer an imported Sprite asset, fall back to wrapping the texture.
            Sprite sprite = Resources.Load<Sprite>(Root + "/" + relativePath);
            if (sprite == null)
            {
                Texture2D tex = LoadTexture(relativePath);
                if (tex != null)
                {
                    sprite = Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height),
                        new Vector2(0.5f, 0.5f), 100f);
                }
            }
            if (sprite != null) _spriteCache[relativePath] = sprite;
            return sprite;
        }

        private static readonly Dictionary<string, Material> _matCache = new Dictionary<string, Material>();

        /// <summary>Load (and cache) a Material asset by its path relative to Resources/Art.</summary>
        public static Material GetMaterial(string relativePath)
        {
            if (string.IsNullOrEmpty(relativePath)) return null;
            if (_matCache.TryGetValue(relativePath, out var cached) && cached != null) return cached;
            Material mat = Resources.Load<Material>(Root + "/" + relativePath);
            if (mat != null) _matCache[relativePath] = mat;
            return mat;
        }

        // --- Convenience category helpers (Prioritizing Genuine AI-Generated Art) ---

        public static Texture2D Character(string heroName) => LoadTexture("Characters/" + heroName) ?? LoadTexture("Characters/" + heroName + "_3D") ?? LoadTexture("Characters/Hero_Rosa_3D");
        // Weapon hero-shot art is authored per catalog entry. Resolution order:
        // exact key -> "<name>_Hero" (new hero-render batch) -> "<name>_3D" (legacy batch) -> generic fallback.
        public static Sprite Weapon(string weaponName) => LoadSprite("Weapons/" + weaponName) ?? LoadSprite("Weapons/" + weaponName + "_Hero") ?? LoadSprite("Weapons/" + weaponName + "_3D") ?? LoadSprite("Weapons/AK47_3D");

        /// <summary>Throwable/throwable icon art. Resolution: exact key -> "<name>_Hero" -> "<name>_3D" -> FragGrenade fallback.</summary>
        public static Sprite Throwable(string throwableName) => LoadSprite("Weapons/Throwables/" + throwableName) ?? LoadSprite("Weapons/Throwables/" + throwableName + "_Hero") ?? LoadSprite("Weapons/Throwables/" + throwableName + "_3D") ?? LoadSprite("Weapons/Throwables/FragGrenade_Hero");

        /// <summary>Weapon attachment icon art. Resolution: exact key -> generic attachment fallback.</summary>
        public static Sprite Attachment(string attachmentName) => LoadSprite("Weapons/Attachments/" + attachmentName) ?? LoadSprite("Weapons/Attachments/" + attachmentName + "_Icon") ?? LoadSprite("Weapons/Attachments/Scope_Default_Icon");

        /// <summary>Weapon skin preview art. Resolution: "<weapon>_<skinName>" -> default hero fallback.</summary>
        public static Sprite WeaponSkin(string weaponName, string skinName) => LoadSprite("Weapons/Skins/" + weaponName + "_" + skinName) ?? Weapon(weaponName);
        public static Sprite Vehicle(string vehicleName) => LoadSprite("Vehicles/" + vehicleName) ?? LoadSprite("Vehicles/" + vehicleName + "_3D") ?? LoadSprite("Vehicles/ArmoredJeep_3D");
        public static Texture2D Terrain(string terrainName) => LoadTexture("Terrain/" + terrainName) ?? LoadTexture("Terrain/IslaVerde_Landscape_3D") ?? LoadTexture("Terrain/Cryo_GlooWall_3D");
        public static Sprite Icon(string iconName) => LoadSprite("UI/Icons/" + iconName) ?? LoadSprite("UI/HUD/HUD_Preview");
        public static Sprite Button(string buttonName) => LoadSprite("UI/Buttons/" + buttonName) ?? LoadSprite("UI/HUD/HUD_Preview");
        public static Sprite Hud(string hudName) => LoadSprite("UI/HUD/" + hudName) ?? LoadSprite("UI/HUD/HUD_Preview");
        public static Texture2D Scene(string sceneArtName) => LoadTexture("Scenes/" + sceneArtName) ?? LoadTexture("Scenes/" + sceneArtName + "_KeyArt") ?? LoadTexture("Scenes/Splash") ?? LoadTexture("Scenes/Splash_KeyArt");
        public static Sprite Loot(string lootName) => LoadSprite("Loot/" + lootName) ?? LoadSprite("Loot/HD_LootCrate_3D");

        /// <summary>Load a real 3D GameObject / Mesh asset from Resources/Models or Resources/Art/3D/.</summary>
        public static GameObject Load3DModel(string relativePath)
        {
            if (string.IsNullOrEmpty(relativePath)) return null;
            GameObject prefab = Resources.Load<GameObject>("Models/" + relativePath) ?? Resources.Load<GameObject>(Root + "/3D/" + relativePath);
            if (prefab != null) return Object.Instantiate(prefab);

            Mesh mesh = Resources.Load<Mesh>("Models/" + relativePath) ?? Resources.Load<Mesh>(Root + "/3D/" + relativePath);
            if (mesh != null)
            {
                GameObject go = new GameObject(relativePath);
                go.AddComponent<MeshFilter>().sharedMesh = mesh;
                MeshRenderer renderer = go.AddComponent<MeshRenderer>();
                Shader s = Shader.Find("Standard");
                if (s == null) s = Shader.Find("Sprites/Default");
                if (s != null) renderer.sharedMaterial = new Material(s);
                return go;
            }
            return new GameObject("Empty_" + relativePath);
        }

        public static GameObject GetCharacterModel(string name) => Load3DModel("Characters/" + name) ?? Load3DModel("Characters/Striker");
        public static GameObject GetWeaponModel(string name) => Load3DModel("Weapons/" + name) ?? Load3DModel("Weapons/AK47");
        public static GameObject GetVehicleModel(string name) => Load3DModel("Vehicles/" + name) ?? Load3DModel("Vehicles/Buggy");
        public static GameObject GetEnvironmentModel(string name) => Load3DModel("Environment/" + name) ?? Load3DModel("Environment/Crate");
        public static GameObject GetPropModel(string name) => Load3DModel("Props/" + name) ?? Load3DModel("Props/Crate");
        public static GameObject GetPrimitive3D(string shape) => Load3DModel("Primitives/" + shape) ?? Load3DModel("Primitives/Cube");

        public static void ClearCache()
        {
            _texCache.Clear();
            _spriteCache.Clear();
            Resources.UnloadUnusedAssets();
        }
    }
}


