using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using UnityEngine.EventSystems;
using BloodRing.Art;

/// <summary>
/// Places a real, pre-authored Blood Ring backdrop texture (from Resources/Art/Scenes)
/// behind each scene's UI. All art is shipped PNG content - none is generated by code.
/// </summary>
public class SceneArtBackdrop : MonoBehaviour
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void Install()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
        AddToScene(SceneManager.GetActiveScene().name);
    }

    private static void OnSceneLoaded(Scene scene, LoadSceneMode mode) => AddToScene(scene.name);

    private static void AddToScene(string sceneName)
    {
        if (GameObject.Find("[BloodRing Scene Backdrop]") != null) return;

        Texture2D tex = BloodRingArtLibrary.Scene(ResolveArtName(sceneName));
        if (tex == null) return;

        if (EventSystem.current == null)
        {
            GameObject es = new GameObject("EventSystem");
            es.AddComponent<EventSystem>();
            es.AddComponent<StandaloneInputModule>();
        }

        GameObject canvasGo = new GameObject("[BloodRing Scene Backdrop]");
        Canvas canvas = canvasGo.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = -5000;
        CanvasScaler scaler = canvasGo.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        scaler.matchWidthOrHeight = 0.5f;
        canvasGo.AddComponent<GraphicRaycaster>();

        GameObject rawGo = new GameObject("Backdrop_" + tex.name);
        rawGo.transform.SetParent(canvasGo.transform, false);
        RawImage img = rawGo.AddComponent<RawImage>();
        img.texture = tex;
        img.color = Color.white;
        img.raycastTarget = false;
        RectTransform r = rawGo.GetComponent<RectTransform>();
        r.anchorMin = Vector2.zero; r.anchorMax = Vector2.one;
        r.offsetMin = Vector2.zero; r.offsetMax = Vector2.zero;

        GameObject shadeGo = new GameObject("ReadableShade");
        shadeGo.transform.SetParent(canvasGo.transform, false);
        Image shade = shadeGo.AddComponent<Image>();
        shade.color = new Color(0f, 0f, 0f, 0.18f);
        shade.raycastTarget = false;
        RectTransform sr = shadeGo.GetComponent<RectTransform>();
        sr.anchorMin = Vector2.zero; sr.anchorMax = Vector2.one;
        sr.offsetMin = Vector2.zero; sr.offsetMax = Vector2.zero;
    }

    private static string ResolveArtName(string sceneName)
    {
        switch (sceneName)
        {
            case "SplashScreen":
            case "SplashLogo":
            case "StartupInitialization":
            case "LoginScene":
            case "LoadingScene":
            case "ReconnectErrorScene":
                return "Splash";

            case "MainMenu":
            case "MainLobby":
            case "EventsPage":
            case "ClanSocial":
            case "ProfileScene":
                return "MainLobby";

            case "CharacterSelect":
            case "CharacterPage":
            case "StoreScene":
            case "InventoryScene":
            case "SettingsScene":
                return "CharacterHub";

            case "LobbyScene":
            case "WaitingIsland":
            case "MatchmakingScene":
                return "WaitingIsland";

            case "GameScene":
            case "MainBattleRoyaleMap":
            case "TrainingGround":
                return "BattleMap";

            case "GameOver":
            case "ResultVictoryScreen":
                return "Results";

            default: return sceneName;
        }
    }
}


